blog/config/routes.rb
Rails.application.routes.draw do

  root to: 'home#index'
  resources :home, only: [:index]
  resources :posts, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  resources :post do
    resources :comments, only: [:index, :new, :create, :show, :edit, :update, :destroy]
  end
  resource :about, only: [:show]

end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post #asocjacja :kazdy komentarz nalezy do jednego posta

end

blog/app/models/post.rb
class Post < ActiveRecord::Base

  # validates_presence_of :name, :title
  # validates_length_of :title, :minimum => 5
  validates :name, :title, presence: true
  validates_length_of :title, minimum: 5
  has_many :comments  #moge otrzymac wszystie komentarze dla posta @post.comments, asocjacja:jeden post moze miec wiele komentarzy

end

blog/app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def show

  end
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def redirect
  #  return redirect_to home_index_path
  # end

end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :find_post, :only => [:index, :show, :new, :create, :edit, :update, :destroy]

  def index
    @comments = @post.comments
  end

  def show
    @comment = @post.comments.find(params[:id])
  end

  def new
    @comment = @post.comments.build
  end

  def create
    @comment = @post.comments.build(params_comment)
    if @comment.save
      redirect_to post_comment_url(@post, @comment)
      flash[:notice] = 'Komentarz został dodany!!!'
    else
      render :action => "new"
    end
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(params_comment)
      redirect_to post_comment_url(@post, @comment)
      flash[:notice] = 'Komentarz został pomyślnie edytowany.'
    else
      render :action => "edit"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = 'Komentarz został usunięty.'
    redirect_to post_comments_path(@post)
  end

  private

  def params_comment
    params.require(:comment).permit(:commenter, :body)
  end

  def find_post
    @post = Post.find(params[:post_id])
  end
end

blog/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

blog/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_filter :find_post, :only => [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
    respond_to do |format|
      format.html # index html.slim
      format.xml {render :xml => @posts}
    end
  end
  def new
    @post = Post.new
    respond_to do |format|
      format.html # new.html.slim
      format.xml  { render :xml => @post }
    end
  end

  def create
    #return render text: params[:post]

    @post = Post.new(params_post)
    respond_to do |format|
      if @post.save
        flash[:notice] = 'Post został dodany!!!'
        format.html { redirect_to(@post) }
        format.xml  { render :xml => @post, :status => :created, :location => @post }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.slim
      format.xml  { render :xml => @post }
    end
  end

  def edit
  end


  def update
    respond_to do |format|
      if @post.update(params_post)
        flash[:notice] = 'Post został pomyślnie edytowany.'
        format.html { redirect_to(@post) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @post.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      flash[:notice] = 'Post został usunięty.'
      format.html { redirect_to(posts_url) }
      format.xml  { head :ok }
    end
  end

  private

  def params_post
    params.require(:post).permit(:name, :title, :content)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/views/abouts/show.html.slim
section#abouts
  .container
    .row
      h1
        | O mnie
    .col-md-3
      .polaroid.mar-top
        = image_tag("about_me/tren.jpg")
    .col-md-9
      h4.justify
        | Stworzyłam tą stronę z zamiarem zachęcenia Was do aktywnego spędzania wolnego czasu – zmiany złych nawyków dotyczących żywienia, treningu oraz stylu życia.
        br
          | Poprzez treści tutaj publikowane chciałabym przekazać pozytywną energię, wszystkim tym którzy pragną zdrowo żyć i szukają źródła motywacji. To właśnie odpowiednio ukierunkowana motywacja w połączeniu z wytrwałością i systematycznością stanowią klucz do osiągnięcia sukcesu. Sport jest moją pasją – nie wyobrażam sobie życia bez aktywności fizycznej. Mam nadzieję, że uda mi się przekonać Was do tego, że warto a brak czasu jest jedynie wymówką!
        br
          | Jestem absolwentką Akademii Wychowania Fizycznego w Krakowie. Od dziecka związana jestem ze sportem. Trenowałam piłkę ręczną, siatkówkę – od dziewięciu lat związana jestem z lekkoatletykę biegając na średnich i długich dystansach (800m, 1500m, 3000m z przeszkodami) oraz w biegach przełajowych. Przez większość mojego sportowego życia związana byłam z klubem AZS AWF Kraków.Bieganie jest najbardziej naturalną aktywnością jaka od zawsze towarzyszy człowiekowi. Bieganie zajmuje wysoką pozycję wsród sposobów na połączenie przyjemności z promocją aktywnego trybu życia.
        br
          | Zachęcam Was do regularnego odwiedzania mojej strony – gwarantuję, że informacje, które tutaj znajdziecie pomogą Wam w mobilizacji samych siebie oraz w osiągnięciu wyznaczonych celów.
      h4.right
        | Pozdrawiam,
        p
          | Natalia Pozorska

blog/app/views/comments/edit.html.slim
.container
  .row style="margin-top: 50px"
    h1
      | Edycja komentarza
    = bootstrap_form_for [@post, @comment], layout: :horizontal do |f|
      .col-md-10
        = f.text_field :commenter, label: "Użytkownik:"
        = f.text_area :body, label: "Treść komentarza:"
      .col-md-2.col-md-offset-9
        = f.submit "Dodaj"
  .col-md-6.col-md-offset-3
    nav style="margin-top: 150px"
      ul.pager
        li.previous
          = link_to('<< Wróć do komentarzy', post_comments_path(@post))
        li.next
          = link_to('Zobacz komentarz >>', post_comment_path(@post, @comment))

blog/app/views/comments/index.html.slim
section#posts_comments_index
  .container
    .row
      h1
        | Komentarze dla posta
        b.tit
          =< @post.title
      .col-md-12
        .panel.panel-default
          .panel-heading
            = link_to('Nowy komentarz', new_post_comment_path(@post))
          table.table
            tr
              th
                | Nazwa użytkownika
              th
                | Tresć komentarza

            - @comments.each do | comment |
              tr
                th
                  = comment.commenter
                td.tit.cont
                  = comment.body
                td
                  .dropdown
                    button.btn.btn-default.dropdown-toggle#dropdownMenu1 type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                      | Menu
                      span.caret
                    ul.dropdown-menu aria-labelledby="dropdownMenu1"
                      li
                        a
                          = link_to('Zobacz komentarz', post_comment_path(@post, comment))
                      li
                        a
                          = link_to('Edytuj', edit_post_comment_path(@post, comment))
                      li
                        a
                          = link_to('Usuń', post_comment_path(@post, comment), :method => :delete)
    hr
        .col-md-4
          nav
            ul.pager
              li.previous
                = link_to('<< Wróć do posta', @post)

blog/app/views/comments/new.html.slim
.container
  .row style="margin-top: 50px"
    h1
      | Nowy komentarz
    = bootstrap_form_for [@post, @comment], layout: :horizontal do |f|
      .col-md-10
        = f.text_field :commenter, hide_label: true, placeholder: "Nazwa użytkownika..."
        = f.text_area :body, rows: 6, hide_label: true, placeholder: "Treść komentarza..."
      .col-md-2.col-md-offset-9
        = f.submit "Dodaj"
  hr style="margin-top: 150px"
  .col-md-6
    nav style="margin-top: 15px"
      ul.pager
        li.previous
          = link_to('<< Wróć do komentarzy', post_comments_path(@post))

blog/app/views/comments/show.html.slim
.container
  .row style="margin-top: 50px"
    h1
      | Komentarz do:
      b style="font-style: italic"
        =< @post.title
    .col-md-6.col-md-offset-3
      h4 style="color: #2F5282"
        | Użytkownik:
        b
          =< @comment.commenter
      h4 style="color: #2F5282"
        | Komentarz:
        b style="color: #808080; font-style: italic"
          =< @comment.body
  .col-md-6.col-md-offset-3
    nav style="margin-top: 150px"
      ul.pager
        li.previous
          = link_to('<< Wróć do komentarzy', post_comments_path(@post))
        li.next
          = link_to('Edytuj komentarz >>', edit_post_comment_path(@post, @comment))

blog/app/views/home/index.html.slim
section#home
  .container
    .row
      .col-md-12
        .jumbotron
          h1
            = image_tag("logo.png")
          p
            | Witam!
            br
              | Na blogu znajdziesz wiele przydatnych informacji o tym jak utrzymac formę, wybrac dobrą dietę i utrzymać wagę. Jeżeli bezskutecznie próbujesz schudnąć to trafiłeś w dziesiątkę!
            span.glyphicon.glyphicon-heart-empty aria-hidden="true"
          hr
          p
            span.glyphicon.glyphicon-hand-right aria-hidden="true" style="color: #22A7F0"
            =< link_to('Moje posty', posts_path)
  .row.slid
    .carousel.slide#carousel-example-generic data-ride="carousel"
      .carousel-inner role="listbox"
        .item.active
          .carousel-caption.text-left
            | Poświęć chwilę
            h4
              | POLECANE KATEGORIE >>
        .item
          .carousel-caption.text-left
            | Coś na START
            h4
              =< link_to('Jak zacząć ćwiczyć? >>', "http://www.adriannapalka.pl/category/jak-zaczac-cwiczyc/")
        .item
          .carousel-caption.text-left
            | Wszystko o biegach
            h4
              =< link_to('Bieganie >>', "http://www.adriannapalka.pl/category/bieganie/")
        .item
          .carousel-caption.text-left
            | Dietetycznie, nie znaczy niesmacznie
            h4
              =< link_to('Dieta >>', "http://www.adriannapalka.pl/category/dieta/")

      a.right.carousel-control.prev href="#carousel-example-generic" role="button" data-slide="prev"
        span.glyphicon.glyphicon-chevron-left aria-hidden="true"
        span.sr-only Previous
      a.right.carousel-control.next href="#carousel-example-generic" role="button" data-slide="next"
        span.glyphicon.glyphicon-chevron-right aria-hidden="true"
        span.sr-only Next

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<h1>Moj blog</h1>

</body>
</html>

blog/app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Blog
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    p style="color: green; margin-top: 10px; text-align: center"
      = flash[:notice]
      = render"shared/header"
    = yield
    = render"shared/footer"

blog/app/views/posts/edit.html.slim
section#post_edit
  .container
    .row
      h1
        | Edycja posta
      = bootstrap_form_for @post, layout: :horizontal do |f|
        .col-md-10
          = f.text_field :name, label: "Temat:"
          = f.text_field :title, label: "Tytuł:"
          = f.text_area :content, rows: 10, label: "Treść posta:"
        .col-md-2.col-md-offset-9
          = f.submit "Dodaj"
    hr
    .col-md-6.col-md-offset-3
      nav
        ul.pager
          li.previous
            = link_to('<< Wróć do posta', posts_path)
          li.next
            = link_to('Zobacz post >>', @post)

blog/app/views/posts/index.html.slim
section#posts_comments_index
  .container
    .col-md-12
      .row
        h1
          | Zbiór postów
    .col-md-12.text-left
      .row.margin_top
        = link_to(new_post_path) do
          button.btn.btn-default.btn-np type="button" aria-label="Left Align"
            span.glyphicon.glyphicon-pencil aria-hidden="true"
            | Nowy post

    .col-md-12
      .row.margin_top
        - @posts.each do | post |
          .col-md-4
            .thumbnail
              .img-thu
                = image_tag("s.jpg")
                .caption
                  h3.nam
                    = post.name
                  p.tit
                    = link_to(post_path(post))
                      = post.title
                  p
                    .dropdown
                      button.btn.btn-default.dropdown-toggle#dropdownMenu1 type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"
                        | Menu
                        span.caret
                      ul.dropdown-menu aria-labelledby="dropdownMenu1"
                        li
                          a
                            = link_to('Zobacz post', post)
                        li
                          a
                            = link_to('Edytuj', edit_post_path(post))
                        li
                          a
                            = link_to('Usuń', post, :method => :delete)

blog/app/views/posts/new.html.slim
section#post_new
  .container
    .row
      h1
        | Nowy post
      = bootstrap_form_for @post, layout: :horizontal do |f|
        .col-md-10
          = f.text_field :name, hide_label: true, placeholder: "Temat posta..."
          = f.text_field :title, hide_label: true, placeholder: "Tytuł posta..."
          = f.text_area :content, rows: 10, hide_label: true, placeholder: "Treść posta..."
        .col-md-2.col-md-offset-9
          = f.submit "Dodaj"
    hr
    .col-md-6
      nav
        ul.pager
          li.previous
            = link_to('<< Wróć do postów', posts_path)

blog/app/views/posts/show.html.slim
section#post_show
  .container
    .row
      h1
        | Twój post
    .container
      .col-md-4.col-md-offset-2
        h4
          b
            | TEMAT:
          b.con
            =< @post.name
      .col-md-4.col-md-offset-2
        h4
          b
            | TYTUŁ:
          b.con.ital
            =< @post.title
      .col-md-12.text-justify
        h4.margin_top
          | TREŚĆ POSTA:
        p.con
          =< @post.content
        nav.margin_top
          ul.pager
            .col-md-6
              li.previous
                = link_to('<< Wróć do postów', posts_path)
            .col-md-2.col-md-offset-4
              li.previous
                = link_to('Edytuj post >>', edit_post_path(@post))
    hr
      .col-md-4
        h4.under
          | KOMENTARZE:
        - @post.comments.each do |c|
          p.kom
            b
              | Użytkownik:
            b.con
              =< c.commenter
          p.kom
            b
              | Komentarz:
            b.con.ital
              =< c.body
        nav.margin_top
          ul.pager
            li.previous
              = link_to('Zarządzaj komentarzami', post_comments_path(@post))

blog/app/views/shared/_footer.html.slim
section#footer
  .shadow
    .container
      .row
        .col-md-12
          .padding_top
            ul.list-inline
              .col-md-3
                li
                  | Sponsorzy
              .col-md-3
                li
                  = link_to("http://pl-eu.puma.com/pl/en/home", target:"_blank")
                    = image_tag("loga/2.jpg")
              .col-md-3
                li
                  = link_to("http://www.reebok.pl/", target:"_blank")
                    = image_tag("loga/1.png")
              .col-md-3
                li
                  = link_to("https://www.bwin.com/pl", target:"_blank")
                    = image_tag("loga/7.jpg")
      hr
      .row
        .col-md-12
          ul.list-inline.bottom
            li
              | Copyright by nat@poz
            li
              .border
            li
              span.glyphicon.glyphicon-copyright-mark aria-hidden="true"
              | 2016

blog/app/views/shared/_header.html.slim
section#header
  nav.navbar.navbar-default.navbar-fixed-top.moj
    .container
      .navbar-header
        button.navbar-toggle.collapsed#button_collapsed type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false"
          span.sr-only Toggle navigation
          span.icon-bar
          span.icon-bar
          span.icon-bar
      .collapse.navbar-collapse#bs-example-navbar-collapse-1
        ul.nav.navbar-nav
          li
            span.title
              ' Kontakt
            span.glyphicon.glyphicon-phone aria-hidden="true"
            span.value
              ' 999-888-777
          li.link
            span.title
              '  Napisz do mnie:
            span.glyphicon.glyphicon-envelope aria-hidden="true"
            span.value
              =< raw link_to("natalia.pozorska@cyberkom.pl")
        ul.nav.navbar-nav.navbar-right
          li
            = link_to(home_index_path)
              i.glyphicon.glyphicon-home
              ' Strona główna
          li
            = link_to(posts_path)
              i.glyphicon.glyphicon-book
              | Posty
          li
            = link_to(about_path)
              i.glyphicon.glyphicon-user
              | O mnie